#+PROPERTY: header-args:emacs-lisp :lexical t
* Advent of Code 2020

** Setup

*** Lexical binding

Set lexical binding to apply to all org source blocks in the file by setting :lexical t in the src header

Or set it globally with

#+begin_example
#+PROPERTY: header-args:emacs-lisp :lexical t
#+end_example


*** File Reading

    #+begin_src emacs-lisp

   (defun read-lines (filePath)
     "Return a list of lines of a file at filePath."
     (with-temp-buffer
       (insert-file-contents filePath)
       (split-string (buffer-string) "\n" t)))

    #+end_src

    #+RESULTS:
    : read-lines

** Problems

*** Day 1

**** Part 1

    #+begin_quote
     --- Day 1: Report Repair ---
 After saving Christmas five years in a row, you've decided to take a vacation at a nice resort on a tropical island. Surely, Christmas will go on without you.

 The tropical island has its own currency and is entirely cash-only. The gold coins used there have a little picture of a starfish; the locals just call them stars. None of the currency exchanges seem to have heard of them, but somehow, you'll need to find fifty of these coins by the time you arrive so you can pay the deposit on your room.

 To save your vacation, you need to get all fifty stars by December 25th.

 Collect stars by solving puzzles. Two puzzles will be made available on each day in the Advent calendar; the second puzzle is unlocked when you complete the first. Each puzzle grants one star. Good luck!

 Before you leave, the Elves in accounting just need you to fix your expense report (your puzzle input); apparently, something isn't quite adding up.

 Specifically, they need you to find the two entries that sum to 2020 and then multiply those two numbers together.

 For example, suppose your expense report contained the following:

 1721
 979
 366
 299
 675
 1456
 In this list, the two entries that sum to 2020 are 1721 and 299. Multiplying them together produces 1721 * 299 = 514579, so the correct answer is 514579.

 Of course, your expense report is much larger. Find the two entries that sum to 2020; what do you get if you multiply them together?
    #+end_quote


 Day 1 input: https://adventofcode.com/2020/day/1/input

 #+begin_src emacs-lisp

   (setq input-file-path "../input/1/input.txt")
   (setq goal-sum 2020)

   (defun find-sum-pair (vector goal)
     "Find a pair of items in a vector that add up to goal"
     (let
	 ((x 0) (y 0) (found nil))
       (while (and (not found) (< x (length vector)))
	 (while (and (not found) (< y (length vector)))
	   ;;(message (format "testing %d %d - %d %d" x y (aref vector x) (aref vector y))) 
	   (if (eq (+ (aref vector x) (aref vector y)) goal)
	       (setq found (list (aref vector x) (aref vector y)))
	     (setq y (+ y 1))
	     )
	   )
	 (setq x (+ x 1))
	 (setq y 0)
	 ;;(message (format "setting x to %x" x))
	 )
       found
       )
     )

   (find-sum-pair (vector 8 1 3 5) 6)

   (defun read-lines (filePath)
     "Return a list of lines of a file at filePath."
     (with-temp-buffer
       (insert-file-contents filePath)
       (split-string (buffer-string) "\n" t)))

   (defun read-file-to-number-vector (filepath)
     "Read the input data file, return a vector of numbers"
     (vconcat
      (mapcar 'string-to-number (read-lines filepath))
      )
     )

   (defun day1a-answer (filepath)
     (seq-reduce
      #'*
      (find-sum-pair (read-file-to-number-vector filepath) goal-sum)
      1))

   (day1a-answer input-file-path)
 #+end_src

 #+RESULTS:
 : 703131

**** Part 2

     #+begin_quote
     The Elves in accounting are thankful for your help; one of them even offers you a starfish coin they had left over from a past vacation. They offer you a second one if you can find three numbers in your expense report that meet the same criteria.

Using the above example again, the three entries that sum to 2020 are 979, 366, and 675. Multiplying them together produces the answer, 241861950.

In your expense report, what is the product of the three entries that sum to 2020?
     #+end_quote


#+begin_src emacs-lisp

  ;; Lets do it the hacky way. Recursive would be better

  (defun should-skip (a b c)
    "Skip if any of a b c are the same"
    (or
     (eq a b)
     (eq a c)
     (eq b c)
     )
    )

  (defun find-sum-triplet (vector goal)
    "Find three items in a vector that add up to goal"
    (let
	((x 0) (y 0) (z 0) (found nil))
      (while (and (not found) (< x (length vector)))
	(while (and (not found) (< y (length vector)))
	  (while (and (not found) (< z (length vector)))
	    ;;(message (format "testing %d %d - %d %d" x y (aref vector x) (aref vector y))) 
	    (if (and (not (should-skip x y z)) (eq (+ (aref vector x) (aref vector y) (aref vector z)) goal))
		(setq found (list (aref vector x) (aref vector y) (aref vector z)))
	      (setq z (+ z 1))
	      )
	    )
	  (setq y (+ y 1))
	  (setq z 0)
	  )
	(setq x (+ x 1))
	(setq y 0)
	)
      found
      )
    )

  (find-sum-triplet [1 2 3 4 5] 12)

  (defun day1b-answer (filepath)
    (seq-reduce
     #'*
     (find-sum-triplet (read-file-to-number-vector filepath) goal-sum)
     1))

  (day1b-answer filepath)

#+end_src

#+RESULTS:
: 272423970

*** Day 2

    #+begin_quote
    --- Day 2: Password Philosophy ---
Your flight departs in a few days from the coastal airport; the easiest way down to the coast from here is via toboggan.

The shopkeeper at the North Pole Toboggan Rental Shop is having a bad day. "Something's wrong with our computers; we can't log in!" You ask if you can take a look.

Their password database seems to be a little corrupted: some of the passwords wouldn't have been allowed by the Official Toboggan Corporate Policy that was in effect when they were chosen.

To try to debug the problem, they have created a list (your puzzle input) of passwords (according to the corrupted database) and the corporate policy when that password was set.

For example, suppose you have the following list:

1-3 a: abcde
1-3 b: cdefg
2-9 c: ccccccccc
Each line gives the password policy and then the password. The password policy indicates the lowest and highest number of times a given letter must appear for the password to be valid. For example, 1-3 a means that the password must contain a at least 1 time and at most 3 times.

In the above example, 2 passwords are valid. The middle password, cdefg, is not; it contains no instances of b, but needs at least 1. The first and third passwords are valid: they contain one a or nine c, both within the limits of their respective policies.

How many passwords are valid according to their policies?


    #+end_quote

Input: ~/git/adventofcode2020/input/2/input.txt

#+begin_quote
--- Part Two ---
While it appears you validated the passwords correctly, they don't seem to be what the Official Toboggan Corporate Authentication System is expecting.

The shopkeeper suddenly realizes that he just accidentally explained the password policy rules from his old job at the sled rental place down the street! The Official Toboggan Corporate Policy actually works a little differently.

Each policy actually describes two positions in the password, where 1 means the first character, 2 means the second character, and so on. (Be careful; Toboggan Corporate Policies have no concept of "index zero"!) Exactly one of these positions must contain the given letter. Other occurrences of the letter are irrelevant for the purposes of policy enforcement.

Given the same example list from above:

1-3 a: abcde is valid: position 1 contains a and position 3 does not.
1-3 b: cdefg is invalid: neither position 1 nor position 3 contains b.
2-9 c: ccccccccc is invalid: both position 2 and position 9 contain c.
How many passwords are valid according to the new interpretation of the policies?

#+end_quote


#+begin_src emacs-lisp

  (setq day2--file-path "~/git/adventofcode2020/input/2/input.txt")

  (setq day2--test-data '("1-3 a: abcde" "1-3 b: cdefg" "2-9 c: ccccccccc"))

  (defun day2--parse-line (line)
    "Parse a line into min, max, letter, password in an association list. All entries appear to have the structure 1-3 a: abcde "
    (let (split)
      (setq split (split-string line "[-[:blank:]:]"))
      (list
       (cons 'num1 (string-to-number (nth 0 split)))
       (cons 'num2 (string-to-number (nth 1 split)))
       (cons 'letter (aref (nth 2 split) 0))
       (cons 'password (nth 4 split)))
      )
    )

  ;; (day2--parse-line "1-3 b: cdefg")
  ;; ((min . 1) (max . 3) (letter . 98) (password . "cdefg"))

  (defun day2a--is-valid (min max letter password)
    "Valid if occurrences of letter in password are between min and max inclusive"
    (let (count)
      (setq count (length (seq-filter (lambda (it) (eq it letter)) password)))
      (and (>= count min) (<= count max))
      )
    )

  (defun day2b--is-valid (num1 num2 letter password)
    "Valid if, of the string characters indexed by num1 and num2 (1-indexed), one but not both are equal to letter"
    (xor
     (eq letter (aref password (- num1 1)))
     (eq letter (aref password (- num2 1)))
     )
    )

  ;; (day2b--is-valid 1 3 ?b "abc")
  ;; (day2b--is-valid 1 3 ?c "abc")
  ;; (day2b--is-valid 1 3 ?a "aaa")

  (defun day2--line-is-valid (line validator)
    "Parse an input line and check it against the validator"
    (let (parsed)
      (setq parsed (day2--parse-line line))
      (funcall validator (alist-get 'num1 parsed) (alist-get 'num2 parsed) (alist-get 'letter parsed) (alist-get 'password parsed))
      )
    )

  ;; (day2--line-is-valid "1-3 a: abcde" #'day2a--is-valid) ;;t
  ;; (day2--line-is-valid "1-3 a: abcde" #'day2b--is-valid) ;;t

  ;; (day2--line-is-valid "1-3 a: abade" #'day2a--is-valid) ;;t
  ;; (day2--line-is-valid "1-3 a: abade" #'day2b--is-valid) ;;nil

  (defun day2--valid-line-count (data validator)
    (length (seq-filter (lambda (x) (day2--line-is-valid x validator)) data)))

  (defun day2--solution (filepath validator)
    (day2--valid-line-count (read-lines filepath) validator)

  (defun day2a--solution (filepath)
    (day2--valid-line-count (read-lines filepath) #'day2a--is-valid)) 
  
  (defun day2b--solution (filepath)
    (day2--valid-line-count (read-lines filepath) #'day2b--is-valid)) 

  (message "Part 1 solution: %s" (day2a--solution day2--file-path))
  (message "Part 2 solution: %s" (day2b--solution day2--file-path))
#+end_src

