#+PROPERTY: header-args:emacs-lisp :lexical t
* Advent of Code 2020

** Setup

*** Lexical binding

Set lexical binding to apply to all org source blocks in the file by setting :lexical t in the src header

Or set it globally with

#+begin_example
#+PROPERTY: header-args:emacs-lisp :lexical t
#+end_example


*** File Reading

    #+begin_src emacs-lisp

   (defun read-lines (filePath)
     "Return a list of lines of a file at filePath."
     (with-temp-buffer
       (insert-file-contents filePath)
       (split-string (buffer-string) "\n" t)))

    #+end_src

    #+RESULTS:
    : read-lines

** Problems

*** Day 1

**** Part 1

    #+begin_quote
     --- Day 1: Report Repair ---
 After saving Christmas five years in a row, you've decided to take a vacation at a nice resort on a tropical island. Surely, Christmas will go on without you.

 The tropical island has its own currency and is entirely cash-only. The gold coins used there have a little picture of a starfish; the locals just call them stars. None of the currency exchanges seem to have heard of them, but somehow, you'll need to find fifty of these coins by the time you arrive so you can pay the deposit on your room.

 To save your vacation, you need to get all fifty stars by December 25th.

 Collect stars by solving puzzles. Two puzzles will be made available on each day in the Advent calendar; the second puzzle is unlocked when you complete the first. Each puzzle grants one star. Good luck!

 Before you leave, the Elves in accounting just need you to fix your expense report (your puzzle input); apparently, something isn't quite adding up.

 Specifically, they need you to find the two entries that sum to 2020 and then multiply those two numbers together.

 For example, suppose your expense report contained the following:

 1721
 979
 366
 299
 675
 1456
 In this list, the two entries that sum to 2020 are 1721 and 299. Multiplying them together produces 1721 * 299 = 514579, so the correct answer is 514579.

 Of course, your expense report is much larger. Find the two entries that sum to 2020; what do you get if you multiply them together?
    #+end_quote


 Day 1 input: https://adventofcode.com/2020/day/1/input

 #+begin_src emacs-lisp

   (setq input-file-path "../input/1/input.txt")
   (setq goal-sum 2020)

   (defun find-sum-pair (vector goal)
     "Find a pair of items in a vector that add up to goal"
     (let
	 ((x 0) (y 0) (found nil))
       (while (and (not found) (< x (length vector)))
	 (while (and (not found) (< y (length vector)))
	   ;;(message (format "testing %d %d - %d %d" x y (aref vector x) (aref vector y))) 
	   (if (eq (+ (aref vector x) (aref vector y)) goal)
	       (setq found (list (aref vector x) (aref vector y)))
	     (setq y (+ y 1))
	     )
	   )
	 (setq x (+ x 1))
	 (setq y 0)
	 ;;(message (format "setting x to %x" x))
	 )
       found
       )
     )

   (find-sum-pair (vector 8 1 3 5) 6)

   (defun read-lines (filePath)
     "Return a list of lines of a file at filePath."
     (with-temp-buffer
       (insert-file-contents filePath)
       (split-string (buffer-string) "\n" t)))

   (defun read-file-to-number-vector (filepath)
     "Read the input data file, return a vector of numbers"
     (vconcat
      (mapcar 'string-to-number (read-lines filepath))
      )
     )

   (defun day1a-answer (filepath)
     (seq-reduce
      #'*
      (find-sum-pair (read-file-to-number-vector filepath) goal-sum)
      1))

   (day1a-answer input-file-path)
 #+end_src

 #+RESULTS:
 : 703131

**** Part 2

     #+begin_quote
     The Elves in accounting are thankful for your help; one of them even offers you a starfish coin they had left over from a past vacation. They offer you a second one if you can find three numbers in your expense report that meet the same criteria.

Using the above example again, the three entries that sum to 2020 are 979, 366, and 675. Multiplying them together produces the answer, 241861950.

In your expense report, what is the product of the three entries that sum to 2020?
     #+end_quote


#+begin_src emacs-lisp

  ;; Lets do it the hacky way. Recursive would be better

  (defun should-skip (a b c)
    "Skip if any of a b c are the same"
    (or
     (eq a b)
     (eq a c)
     (eq b c)
     )
    )

  (defun find-sum-triplet (vector goal)
    "Find three items in a vector that add up to goal"
    (let
	((x 0) (y 0) (z 0) (found nil))
      (while (and (not found) (< x (length vector)))
	(while (and (not found) (< y (length vector)))
	  (while (and (not found) (< z (length vector)))
	    ;;(message (format "testing %d %d - %d %d" x y (aref vector x) (aref vector y))) 
	    (if (and (not (should-skip x y z)) (eq (+ (aref vector x) (aref vector y) (aref vector z)) goal))
		(setq found (list (aref vector x) (aref vector y) (aref vector z)))
	      (setq z (+ z 1))
	      )
	    )
	  (setq y (+ y 1))
	  (setq z 0)
	  )
	(setq x (+ x 1))
	(setq y 0)
	)
      found
      )
    )

  (find-sum-triplet [1 2 3 4 5] 12)

  (defun day1b-answer (filepath)
    (seq-reduce
     #'*
     (find-sum-triplet (read-file-to-number-vector filepath) goal-sum)
     1))

  (day1b-answer filepath)

#+end_src

#+RESULTS:
: 272423970

*** Day 2

    #+begin_quote
    --- Day 2: Password Philosophy ---
Your flight departs in a few days from the coastal airport; the easiest way down to the coast from here is via toboggan.

The shopkeeper at the North Pole Toboggan Rental Shop is having a bad day. "Something's wrong with our computers; we can't log in!" You ask if you can take a look.

Their password database seems to be a little corrupted: some of the passwords wouldn't have been allowed by the Official Toboggan Corporate Policy that was in effect when they were chosen.

To try to debug the problem, they have created a list (your puzzle input) of passwords (according to the corrupted database) and the corporate policy when that password was set.

For example, suppose you have the following list:

1-3 a: abcde
1-3 b: cdefg
2-9 c: ccccccccc
Each line gives the password policy and then the password. The password policy indicates the lowest and highest number of times a given letter must appear for the password to be valid. For example, 1-3 a means that the password must contain a at least 1 time and at most 3 times.

In the above example, 2 passwords are valid. The middle password, cdefg, is not; it contains no instances of b, but needs at least 1. The first and third passwords are valid: they contain one a or nine c, both within the limits of their respective policies.

How many passwords are valid according to their policies?


    #+end_quote

Input: ~/git/adventofcode2020/input/2/input.txt

#+begin_quote
--- Part Two ---
While it appears you validated the passwords correctly, they don't seem to be what the Official Toboggan Corporate Authentication System is expecting.

The shopkeeper suddenly realizes that he just accidentally explained the password policy rules from his old job at the sled rental place down the street! The Official Toboggan Corporate Policy actually works a little differently.

Each policy actually describes two positions in the password, where 1 means the first character, 2 means the second character, and so on. (Be careful; Toboggan Corporate Policies have no concept of "index zero"!) Exactly one of these positions must contain the given letter. Other occurrences of the letter are irrelevant for the purposes of policy enforcement.

Given the same example list from above:

1-3 a: abcde is valid: position 1 contains a and position 3 does not.
1-3 b: cdefg is invalid: neither position 1 nor position 3 contains b.
2-9 c: ccccccccc is invalid: both position 2 and position 9 contain c.
How many passwords are valid according to the new interpretation of the policies?

#+end_quote


#+begin_src emacs-lisp

  (setq day2--file-path "~/git/adventofcode2020/input/2/input.txt")

  (setq day2--test-data '("1-3 a: abcde" "1-3 b: cdefg" "2-9 c: ccccccccc"))

  (defun day2--parse-line (line)
    "Parse a line into min, max, letter, password in an association list. All entries appear to have the structure 1-3 a: abcde "
    (let (split)
      (setq split (split-string line "[-[:blank:]:]"))
      (list
       (cons 'num1 (string-to-number (nth 0 split)))
       (cons 'num2 (string-to-number (nth 1 split)))
       (cons 'letter (aref (nth 2 split) 0))
       (cons 'password (nth 4 split)))
      )
    )

  ;; (day2--parse-line "1-3 b: cdefg")
  ;; ((min . 1) (max . 3) (letter . 98) (password . "cdefg"))

  (defun day2a--is-valid (min max letter password)
    "Valid if occurrences of letter in password are between min and max inclusive"
    (let (count)
      (setq count (length (seq-filter (lambda (it) (eq it letter)) password)))
      (and (>= count min) (<= count max))
      )
    )

  (defun day2b--is-valid (num1 num2 letter password)
    "Valid if, of the string characters indexed by num1 and num2 (1-indexed), one but not both are equal to letter"
    (xor
     (eq letter (aref password (- num1 1)))
     (eq letter (aref password (- num2 1)))
     )
    )

  ;; (day2b--is-valid 1 3 ?b "abc")
  ;; (day2b--is-valid 1 3 ?c "abc")
  ;; (day2b--is-valid 1 3 ?a "aaa")

  (defun day2--line-is-valid (line validator)
    "Parse an input line and check it against the validator"
    (let (parsed)
      (setq parsed (day2--parse-line line))
      (funcall validator (alist-get 'num1 parsed) (alist-get 'num2 parsed) (alist-get 'letter parsed) (alist-get 'password parsed))
      )
    )

  ;; (day2--line-is-valid "1-3 a: abcde" #'day2a--is-valid) ;;t
  ;; (day2--line-is-valid "1-3 a: abcde" #'day2b--is-valid) ;;t

  ;; (day2--line-is-valid "1-3 a: abade" #'day2a--is-valid) ;;t
  ;; (day2--line-is-valid "1-3 a: abade" #'day2b--is-valid) ;;nil

  (defun day2--valid-line-count (data validator)
    (length (seq-filter (lambda (x) (day2--line-is-valid x validator)) data)))

  (defun day2--solution (filepath validator)
    (day2--valid-line-count (read-lines filepath) validator)

  (defun day2a--solution (filepath)
    (day2--valid-line-count (read-lines filepath) #'day2a--is-valid)) 
  
  (defun day2b--solution (filepath)
    (day2--valid-line-count (read-lines filepath) #'day2b--is-valid)) 

  (message "Part 1 solution: %s" (day2a--solution day2--file-path))
  (message "Part 2 solution: %s" (day2b--solution day2--file-path))
#+end_src

*** Day 3

    #+begin_quote
    --- Day 3: Toboggan Trajectory ---
With the toboggan login problems resolved, you set off toward the airport. While travel by toboggan might be easy, it's certainly not safe: there's very minimal steering and the area is covered in trees. You'll need to see which angles will take you near the fewest trees.

Due to the local geology, trees in this area only grow on exact integer coordinates in a grid. You make a map (your puzzle input) of the open squares (.) and trees (#) you can see. For example:

..##.......
#...#...#..
.#....#..#.
..#.#...#.#
.#...##..#.
..#.##.....
.#.#.#....#
.#........#
#.##...#...
#...##....#
.#..#...#.#
These aren't the only trees, though; due to something you read about once involving arboreal genetics and biome stability, the same pattern repeats to the right many times:

..##.........##.........##.........##.........##.........##.......  --->
#...#...#..#...#...#..#...#...#..#...#...#..#...#...#..#...#...#..
.#....#..#..#....#..#..#....#..#..#....#..#..#....#..#..#....#..#.
..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#
.#...##..#..#...##..#..#...##..#..#...##..#..#...##..#..#...##..#.
..#.##.......#.##.......#.##.......#.##.......#.##.......#.##.....  --->
.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#
.#........#.#........#.#........#.#........#.#........#.#........#
#.##...#...#.##...#...#.##...#...#.##...#...#.##...#...#.##...#...
#...##....##...##....##...##....##...##....##...##....##...##....#
.#..#...#.#.#..#...#.#.#..#...#.#.#..#...#.#.#..#...#.#.#..#...#.#  --->
You start on the open square (.) in the top-left corner and need to reach the bottom (below the bottom-most row on your map).

The toboggan can only follow a few specific slopes (you opted for a cheaper model that prefers rational numbers); start by counting all the trees you would encounter for the slope right 3, down 1:

From your starting position at the top-left, check the position that is right 3 and down 1. Then, check the position that is right 3 and down 1 from there, and so on until you go past the bottom of the map.

The locations you'd check in the above example are marked here with O where there was an open square and X where there was a tree:

..##.........##.........##.........##.........##.........##.......  --->
#..O#...#..#...#...#..#...#...#..#...#...#..#...#...#..#...#...#..
.#....X..#..#....#..#..#....#..#..#....#..#..#....#..#..#....#..#.
..#.#...#O#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#..#.#...#.#
.#...##..#..X...##..#..#...##..#..#...##..#..#...##..#..#...##..#.
..#.##.......#.X#.......#.##.......#.##.......#.##.......#.##.....  --->
.#.#.#....#.#.#.#.O..#.#.#.#....#.#.#.#....#.#.#.#....#.#.#.#....#
.#........#.#........X.#........#.#........#.#........#.#........#
#.##...#...#.##...#...#.X#...#...#.##...#...#.##...#...#.##...#...
#...##....##...##....##...#X....##...##....##...##....##...##....#
.#..#...#.#.#..#...#.#.#..#...X.#.#..#...#.#.#..#...#.#.#..#...#.#  --->
In this example, traversing the map using this slope would cause you to encounter 7 trees.

Starting at the top-left corner of your map and following a slope of right 3 and down 1, how many trees would you encounter?


    #+end_quote

    #+begin_quote
    --- Part Two ---
Time to check the rest of the slopes - you need to minimize the probability of a sudden arboreal stop, after all.

Determine the number of trees you would encounter if, for each of the following slopes, you start at the top-left corner and traverse the map all the way to the bottom:

Right 1, down 1.
Right 3, down 1. (This is the slope you already checked.)
Right 5, down 1.
Right 7, down 1.
Right 1, down 2.
In the above example, these slopes would find 2, 7, 3, 4, and 2 tree(s) respectively; multiplied together, these produce the answer 336.

What do you get if you multiply together the number of trees encountered on each of the listed slopes?
    #+end_quote

    #+begin_src emacs-lisp

	    (setq day3--input-filepath "~/git/adventofcode2020/input/3/input.txt")

	    (setq day3--test-input-lines (list 
	    "..##......."
	    "#...#...#.."
	    ".#....#..#."
	    "..#.#...#.#"
	    ".#...##..#."
	    "..#.##....."
	    ".#.#.#....#"
	    ".#........#"
	    "#.##...#..."
	    "#...##....#"
	    ".#..#...#.#"
	    )
      )
	       ;; (defun read-lines (filePath)
	       ;;   "Return a list of lines of a file at filePath."
	       ;;   (with-temp-buffer
	       ;;     (insert-file-contents filePath)
	       ;;     (split-string (buffer-string) "\n" t)))

	    (defun day3--vectorize-map-data-lines (map-data-lines)
	    "Convert input data lines to a vector of strings; strings can be treated as arrays so essentially a 2d-array of chars"
	      (vconcat map-data-lines)
	      )


	    (defun day3--make-slope (x y)
		  "List representing a slope of y/x"
		  (list x y)
		  )

	    (defun day3--make-position (x y)
		  "List representing a position. Can extend past map-data boundary"
		  (list x y)
		  )

	    (defun day3--get-x (coordinate)
		  "Get x-value of coordinate or slope. Don't take into account GCD of slope parts"
		  (car coordinate)
		  )

	    (defun day3--get-y (coordinate)
		  (nth 1 coordinate)
		  )

	    (defun day3--is-tree (map-data position)
	      "Determine whether xy entry (0-indexed) in map-data is a tree (signified by #)"
	      (eq ?# (aref (aref map-data (day3--get-y position)) (day3--get-x position))))

	    (setq day3--test-map-data (day3--vectorize-map-data-lines day3--test-input-lines))

	    (day3--is-tree day3--test-map-data (day3--make-position 0 0)) ;;nil
	    (day3--is-tree day3--test-map-data (day3--make-position 1 2)) ;;t


	    (defun day3--make-map-data-position (position map-data)
		  "Make a position representing the corresponding entry in map-data, assuming the map wraps to the right"
		  (day3--make-position
		   (% (day3--get-x position) (length (aref map-data 0)))
	     (day3--get-y position)
		   ))

	    (length (aref day3--test-map-data 0))

	    (day3--make-map-data-position
	     (day3--make-position 50 2)
	     day3--test-map-data
	     )

	    (defun day3--increment-position (position slope)
	      (day3--make-position
	       (+ (day3--get-x position) (day3--get-x slope))
	       (+ (day3--get-y position) (day3--get-y slope))
	       ))


	    (defun day3--count-trees-in-descent (start-position map-data slope)
	      "Descend!"
	      (let (position (count 0))
		(setq position start-position)
		(while (< (day3--get-y position) (length map-data))
		  ;;(message "Testing %d %d" (day3--get-x position) (day3--get-y position))
		  (if (day3--is-tree map-data (day3--make-map-data-position position map-data))
		      (setq count (+ count 1)))
		  (setq position (day3--increment-position position slope))
		  )
		count
		))


	    (day3--count-trees-in-descent
	     (day3--make-position 0 0)
	     day3--test-map-data
	     (day3--make-slope 3 1)
	     )

	    (defun day3a--solution (file-path)
	      (day3--count-trees-in-descent
	       (day3--make-position 0 0)
	       (day3--vectorize-map-data-lines (read-lines file-path)) 
	       (day3--make-slope 3 1)
	       )
	      )

	    (day3a--solution day3--input-filepath)

	    (defun day3b--calculate (map-data)
	      (let (start-position)
		(setq start-position (day3--make-position 0 0))
		(*
		 (day3--count-trees-in-descent start-position map-data (day3--make-slope 1 1))
		 (day3--count-trees-in-descent start-position map-data (day3--make-slope 3 1))
		 (day3--count-trees-in-descent start-position map-data (day3--make-slope 5 1))
		 (day3--count-trees-in-descent start-position map-data (day3--make-slope 7 1))
		 (day3--count-trees-in-descent start-position map-data (day3--make-slope 1 2))
		 )
		)
	      )

	    (day3b--calculate day3--test-map-data) ;;336

	    (defun day3b--solution (file-path)
	      (day3b--calculate (day3--vectorize-map-data-lines (read-lines file-path)) ))

	    (day3b--solution day3--input-filepath)
    #+end_src

*** Day 4

    #+begin_quote
    --- Day 4: Passport Processing ---
You arrive at the airport only to realize that you grabbed your North Pole Credentials instead of your passport. While these documents are extremely similar, North Pole Credentials aren't issued by a country and therefore aren't actually valid documentation for travel in most of the world.

It seems like you're not the only one having problems, though; a very long line has formed for the automatic passport scanners, and the delay could upset your travel itinerary.

Due to some questionable network security, you realize you might be able to solve both of these problems at the same time.

The automatic passport scanners are slow because they're having trouble detecting which passports have all required fields. The expected fields are as follows:

byr (Birth Year)
iyr (Issue Year)
eyr (Expiration Year)
hgt (Height)
hcl (Hair Color)
ecl (Eye Color)
pid (Passport ID)
cid (Country ID)
Passport data is validated in batch files (your puzzle input). Each passport is represented as a sequence of key:value pairs separated by spaces or newlines. Passports are separated by blank lines.

Here is an example batch file containing four passports:

ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
byr:1937 iyr:2017 cid:147 hgt:183cm

iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
hcl:#cfa07d byr:1929

hcl:#ae17e1 iyr:2013
eyr:2024
ecl:brn pid:760753108 byr:1931
hgt:179cm

hcl:#cfa07d eyr:2025 pid:166559648
iyr:2011 ecl:brn hgt:59in
The first passport is valid - all eight fields are present. The second passport is invalid - it is missing hgt (the Height field).

The third passport is interesting; the only missing field is cid, so it looks like data from North Pole Credentials, not a passport at all! Surely, nobody would mind if you made the system temporarily ignore missing cid fields. Treat this "passport" as valid.

The fourth passport is missing two fields, cid and byr. Missing cid is fine, but missing any other field is not, so this passport is invalid.

According to the above rules, your improved system would report 2 valid passports.

Count the number of valid passports - those that have all required fields. Treat cid as optional. In your batch file, how many passports are valid?

    #+end_quote

    #+begin_quote
    --- Part Two ---
The line is moving more quickly now, but you overhear airport security talking about how passports with invalid data are getting through. Better add some data validation, quick!

You can continue to ignore the cid field, but each other field has strict rules about what values are valid for automatic validation:

byr (Birth Year) - four digits; at least 1920 and at most 2002.
iyr (Issue Year) - four digits; at least 2010 and at most 2020.
eyr (Expiration Year) - four digits; at least 2020 and at most 2030.
hgt (Height) - a number followed by either cm or in:
If cm, the number must be at least 150 and at most 193.
If in, the number must be at least 59 and at most 76.
hcl (Hair Color) - a # followed by exactly six characters 0-9 or a-f.
ecl (Eye Color) - exactly one of: amb blu brn gry grn hzl oth.
pid (Passport ID) - a nine-digit number, including leading zeroes.
cid (Country ID) - ignored, missing or not.
Your job is to count the passports where all required fields are both present and valid according to the above rules. Here are some example values:

byr valid:   2002
byr invalid: 2003

hgt valid:   60in
hgt valid:   190cm
hgt invalid: 190in
hgt invalid: 190

hcl valid:   #123abc
hcl invalid: #123abz
hcl invalid: 123abc

ecl valid:   brn
ecl invalid: wat

pid valid:   000000001
pid invalid: 0123456789
Here are some invalid passports:

eyr:1972 cid:100
hcl:#18171d ecl:amb hgt:170 pid:186cm iyr:2018 byr:1926

iyr:2019
hcl:#602927 eyr:1967 hgt:170cm
ecl:grn pid:012533040 byr:1946

hcl:dab227 iyr:2012
ecl:brn hgt:182cm pid:021572410 eyr:2020 byr:1992 cid:277

hgt:59cm ecl:zzz
eyr:2038 hcl:74454a iyr:2023
pid:3556412378 byr:2007
Here are some valid passports:

pid:087499704 hgt:74in ecl:grn iyr:2012 eyr:2030 byr:1980
hcl:#623a2f

eyr:2029 ecl:blu cid:129 byr:1989
iyr:2014 pid:896056539 hcl:#a97842 hgt:165cm

hcl:#888785
hgt:164cm byr:2001 iyr:2015 cid:88
pid:545766238 ecl:hzl
eyr:2022

iyr:2010 hgt:158cm hcl:#b6652a ecl:blu byr:1944 eyr:2021 pid:093154719
Count the number of valid passports - those that have all required fields and valid values. Continue to treat cid as optional. In your batch file, how many passports are valid?
    #+end_quote

    #+begin_src emacs-lisp

      (setq day4--required-fields '(
				    "byr"
				    "iyr"  
				    "eyr"
				    "hgt"
				    "hcl"
				    "ecl"
				    "pid"
				    ))

      (setq day4--sample-data-lines '(
				      ""
				      "ecl:gry pid:860033327 eyr:2020 hcl:#fffffd"
				      "byr:1937 iyr:2017 cid:147 hgt:183cm"
				      ""
				      "iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884"
				      "hcl:#cfa07d byr:1929"
				      ""
				      "hcl:#ae17e1 iyr:2013"
				      "eyr:2024"
				      "ecl:brn pid:760753108 byr:1931"
				      "hgt:179cm"
				      ""
				      "hcl:#cfa07d eyr:2025 pid:166559648"
				      "iyr:2011 ecl:brn hgt:59in"
				      ))

      (defun read-lines-with-blanks (filePath)
	"Return a list of lines of a file at filePath, retaining empty lines."
	(with-temp-buffer
	  (insert-file-contents filePath)
	  (split-string (buffer-string) "\n" nil)))

      (defun day4--passport-has-required-fields (passport required-fields)
	"Return true if all strings in list required-fields are present as keys in alist passport"
	;;(message "validating %s" passport)
	(seq-every-p (lambda (x) (member x (map-keys passport))) required-fields))

      (defun day4--alist-from-line (line)
	(mapcar
	 (lambda (x) 
	   (let ((split (split-string x ":")))
	     (cons (pop split) (pop split))))
	 (split-string line)
	 )
	)

      (defun day4--make-passports-from-input (lines)
	"Return a list of passports, where a passport is an alist of string keys/string values of passport fields"
	(let (
	      (acc nil)
	      (passports nil)
	      )
	  (dolist (line lines)
	    ;;(message "line: %s, typeof: %s" line (type-of line))
	    (if (or (eq (length line) 0) (eq line nil))
		(progn
		  ;;(message "current acc: %s" acc)
		  ;;(message "current passports: %s" passports)
		  (when acc
		    (push acc passports)
		    (setq acc nil)
		    )
		  )
	      (setq acc (append acc (day4--alist-from-line line))))
	    )
	  passports
	  )
	)

      (defun day4b--passport-is-valid (passport)
	(let (result)
	(setq result (and
	 (day4--passport-has-required-fields passport day4--required-fields)
	 (day4--validate-birth-year (cdr (assoc "byr" passport)))
	 (day4--validate-issue-year (cdr (assoc  "iyr" passport)))
	 (day4--validate-expiration-year (cdr (assoc "eyr" passport)))
	 (day4--validate-height (cdr (assoc "hgt" passport)))
	 (day4--validate-hair-color (cdr (assoc "hcl" passport)))
	 (day4--validate-eye-color (cdr (assoc "ecl" passport)))
	 (day4--validate-passport-id (cdr (assoc "pid" passport)))))
	(message "passport: %s result: %s" passport result)
	result
	)
	)

      (defun day4a--passport-is-valid (passport)
	(day4--passport-has-required-fields passport day4--required-fields))

      (defun day4--validate-birth-year (x)
	(let ((num (string-to-number x)))
	  (and
	   (string-match (rx (repeat 4 digit)) x)
	   (<= num 2002)
	   (>= num 1920)
	   )
	  )
	)

      (defun day4--validate-issue-year (x)
	(let ((num (string-to-number x)))
	  (and
	   (string-match (rx (repeat 4 digit)) x)
	   (<= num 2020)
	   (>= num 2010)
	   )
	  )
	)

      (defun day4--validate-expiration-year (x)
	(let ((num (string-to-number x)))
	  (and
	   (eq (string-match (rx (repeat 4 digit)) x) 0)
	   (<= num 2030)
	   (>= num 2020)
	   )
	  )
	)

      (defun day4--validate-height (x)
	;;(debug)
	(and
	 (eq (string-match (rx (+ digit) (| "in" "cm")) x) 0)
	 (let ((unit (substring x -2 nil))
	       (val (string-to-number (substring x 0 -2))))
	   ;;(message "val: %d unit: %s" val unit)
	   (if (equal unit "in")
	       (and (>= val 59) (<= val 76))
	     (and (>= val 150) (<= val 193)) ;;cm
	     )
	   )
	 )
	)

      (defun day4--validate-hair-color (x)
	(eq (string-match (rx "#" (repeat 6 (in "0-9" "a-f")) line-end) x) 0))

      (defun day4--validate-eye-color (x)
	(eq (string-match (rx (| "amb" "blu" "brn" "gry" "grn" "hzl" "oth") line-end) x) 0))

      (defun day4--validate-passport-id (x)
	(eq (string-match (rx (repeat 9 digit) line-end) x) 0))

      (setq day4b--sample-invalid-lines (list
      "eyr:1972 cid:100"
      "hcl:#18171d ecl:amb hgt:170 pid:186cm iyr:2018 byr:1926"
      ""
      "iyr:2019"
      "hcl:#602927 eyr:1967 hgt:170cm"
      "ecl:grn pid:012533040 byr:1946"
      ""
      "hcl:dab227 iyr:2012"
      "ecl:brn hgt:182cm pid:021572410 eyr:2020 byr:1992 cid:277"
      ""
      "hgt:59cm ecl:zzz"
      "eyr:2038 hcl:74454a iyr:2023"
      "pid:3556412378 byr:2007"
      ))

      (setq day4b--sample-valid-lines (list
      "pid:087499704 hgt:74in ecl:grn iyr:2012 eyr:2030 byr:1980"
      "hcl:#623a2f"
      ""
      "eyr:2029 ecl:blu cid:129 byr:1989"
      "iyr:2014 pid:896056539 hcl:#a97842 hgt:165cm"
      ""
      "hcl:#888785"
      "hgt:164cm byr:2001 iyr:2015 cid:88"
      "pid:545766238 ecl:hzl"
      "eyr:2022"
      ""
      "iyr:2010 hgt:158cm hcl:#b6652a ecl:blu byr:1944 eyr:2021" "pid:093154719"				   
      ""
      ))

      ;;should be 4
      (length (seq-filter (lambda (x) (day4b--passport-is-valid x))
			  (day4--make-passports-from-input day4b--sample-valid-lines)
			  ))

      ;;should be 0
      (length (seq-filter (lambda (x) (day4b--passport-is-valid x))
			  (day4--make-passports-from-input day4b--sample-invalid-lines)
			  ))

      (setq day4--input-filepath "~/git/adventofcode2020/input/4/input.txt")
      (setq day4--input-lines (read-lines day4--input-filepath))

      (defun day4a--solution (filepath)
	(length (seq-filter
		 (lambda (x) (day4a--passport-is-valid x))
		 (day4--make-passports-from-input (read-lines-with-blanks filepath)))))

      (defun day4b--solution (filepath)
	(length (seq-filter
		 (lambda (x) (day4b--passport-is-valid x))
		 (day4--make-passports-from-input (read-lines-with-blanks filepath)))))

      (day4a--solution day4--input-filepath)
      (day4b--solution day4--input-filepath)

  #+end_src

*** Day 5

    #+begin_quote
    --- Day 5: Binary Boarding ---
You board your plane only to discover a new problem: you dropped your boarding pass! You aren't sure which seat is yours, and all of the flight attendants are busy with the flood of people that suddenly made it through passport control.

You write a quick program to use your phone's camera to scan all of the nearby boarding passes (your puzzle input); perhaps you can find your seat through process of elimination.

Instead of zones or groups, this airline uses binary space partitioning to seat people. A seat might be specified like FBFBBFFRLR, where F means "front", B means "back", L means "left", and R means "right".

The first 7 characters will either be F or B; these specify exactly one of the 128 rows on the plane (numbered 0 through 127). Each letter tells you which half of a region the given seat is in. Start with the whole list of rows; the first letter indicates whether the seat is in the front (0 through 63) or the back (64 through 127). The next letter indicates which half of that region the seat is in, and so on until you're left with exactly one row.

For example, consider just the first seven characters of FBFBBFFRLR:

Start by considering the whole range, rows 0 through 127.
F means to take the lower half, keeping rows 0 through 63.
B means to take the upper half, keeping rows 32 through 63.
F means to take the lower half, keeping rows 32 through 47.
B means to take the upper half, keeping rows 40 through 47.
B keeps rows 44 through 47.
F keeps rows 44 through 45.
The final F keeps the lower of the two, row 44.
The last three characters will be either L or R; these specify exactly one of the 8 columns of seats on the plane (numbered 0 through 7). The same process as above proceeds again, this time with only three steps. L means to keep the lower half, while R means to keep the upper half.

For example, consider just the last 3 characters of FBFBBFFRLR:

Start by considering the whole range, columns 0 through 7.
R means to take the upper half, keeping columns 4 through 7.
L means to take the lower half, keeping columns 4 through 5.
The final R keeps the upper of the two, column 5.
So, decoding FBFBBFFRLR reveals that it is the seat at row 44, column 5.

Every seat also has a unique seat ID: multiply the row by 8, then add the column. In this example, the seat has ID 44 * 8 + 5 = 357.

Here are some other boarding passes:

BFFFBBFRRR: row 70, column 7, seat ID 567.
FFFBBBFRRR: row 14, column 7, seat ID 119.
BBFFBBFRLL: row 102, column 4, seat ID 820.
As a sanity check, look through your list of boarding passes. What is the highest seat ID on a boarding pass?

    #+end_quote

    #+begin_quote
    Ding! The "fasten seat belt" signs have turned on. Time to find your seat.

It's a completely full flight, so your seat should be the only missing boarding pass in your list. However, there's a catch: some of the seats at the very front and back of the plane don't exist on this aircraft, so they'll be missing from your list as well.

Your seat wasn't at the very front or back, though; the seats with IDs +1 and -1 from yours will be in your list.

What is the ID of your seat?
    #+end_quote

    #+begin_src emacs-lisp
      (setq day5--input-filepath "~/git/adventofcode2020/input/5/input.txt")

      (defun day5--convert-stringy-binary-to-int (data zero-char one-char)
	"Convert string of chars representing zero/one in binary to an int"
	(let (binary-string)
	  (setq binary-string (concat [?# ?b]
				      (mapcar (lambda (x) (if (eq zero-char x) ?0 ?1)) data)))
	  (eval (car (read-from-string binary-string)))))

      (day5--convert-stringy-binary-to-int "FBFBBFF" ?F ?B)

      (substring "FBFBBFFRLR" -3 nil)

      (defun day5a--seatnum-from-boarding-pass (boarding-pass)
	(let ((row-string (substring boarding-pass 0 -3))
	      (column-string (substring boarding-pass -3 nil)))
	  (+
	   (* 8(day5--convert-stringy-binary-to-int row-string ?F ?B))
	   (day5--convert-stringy-binary-to-int column-string ?L ?R))))

      (day5a--seatnum-from-boarding-pass "BFFFBBFRRR")

      (defun day5a--get-highest-seat-number (boarding-passes)
	(seq-max (mapcar #'day5a--seatnum-from-boarding-pass boarding-passes)))

      (setq day5a--sample-boarding-passes
	    (list
	     "BFFFBBFRRR"
	     "FFFBBBFRRR"
	     "BBFFBBFRLL"
	     ))

      (day5a--get-highest-seat-number day5a--sample-boarding-passes)

      (defun day5a--solution ()
	(day5a--get-highest-seat-number (read-lines day5--input-filepath)))

      (defun day5b--make-seating-vector (occupied-seat-numbers max-seats)
	"Return an int vector of max-seat-length with empty seats nil, full seats t"
	(let ((seating-vector (make-vector max-seats nil)))
	  (dolist (occupied-seat-number occupied-seat-numbers seating-vector)
	    (aset seating-vector occupied-seat-number t)
	    )
	  )
	)

      (day5b--make-seating-vector '(2 3 5 6) 8)

      (defun day5b--find-seat (seating-vector)
	(let ((is-valid-seating nil)
	      (found nil)
	      (i 0)
	      (seat-full nil))
	  (while (and (not found) (< i (length seating-vector)))
	    (setq seat-full (aref seating-vector i))
	    ;;(message "index %s, is-valid-seating %s, seat-full %s" i is-valid-seating seat-full)
	    (if (and is-valid-seating (not seat-full))
		(setq found i))
	    (if (and (not is-valid-seating) seat-full)
		(setq is-valid-seating t))
	    (setq i (+ 1 i))
	    )
	  found
	  )
	)

      (day5b--find-seat (day5b--make-seating-vector '(2 3 5 6) 8))

      (defun day5b--solution ()
	(day5b--find-seat
	 (day5b--make-seating-vector
	  (mapcar #'day5a--seatnum-from-boarding-pass (read-lines day5--input-filepath))
	  (* 128 8)
	  )))

      (day5a--solution)
      (day5b--solution)

      (defun day5--tricky-convert-boarding-pass-to-int (boarding-pass)
	(let (
	      (conversion-map '((?F . ?0) (?B . ?1) (?L . ?0) (?R . ?1))))
	  (eval (car (read-from-string
		      (concat
		       [?# ?b]
		       (mapcar (lambda (x) (alist-get x conversion-map)) boarding-pass)))))))

      (day5--tricky-convert-boarding-pass-to-int "BBFFBBFRLL")

      (defun day5b--trickier-solution ()
	(day5b--find-seat
	 (day5b--make-seating-vector
	  (mapcar #'day5--tricky-convert-boarding-pass-to-int (read-lines day5--input-filepath))
	  (* 128 8)
	  )))

      (day5b--trickier-solution)
    #+end_src
